version: '3.8'

services:
  video-service:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      API_DOMAIN: ${API_DOMAIN}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      CLOUDFRONT_DOMAIN: ${CLOUDFRONT_DOMAIN}
      MAX_FILE_SIZE: ${MAX_FILE_SIZE}
      ALLOWED_VIDEO_TYPES: ${ALLOWED_VIDEO_TYPES} 