version: '3.8'

services:
  video-service:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    env_file:
      - .env
    # Add your other env vars from .env here 